webtalk_init -webtalk_dir /home/hirangren/Documents/Git/capstone-schwarz/hw/fft/fft.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue May 26 12:41:13 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210996379_0_0_751" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "18010fgfs5cg9h3tut7bep463m" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.4_7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 14.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2400.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1431391560000" -context "sdk\\\\bsp/1431391560000"
webtalk_add_data -client sdk -key hwid -value "1431375311000" -context "sdk\\\\bsp/1431391560000"
webtalk_add_data -client sdk -key os -value "freertos_zynq" -context "sdk\\\\bsp/1431391560000"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1431391560000"
webtalk_transmit -clientid 2274590536 -regid "210996379_0_0_751" -xml /home/hirangren/Documents/Git/capstone-schwarz/hw/fft/fft.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/hirangren/Documents/Git/capstone-schwarz/hw/fft/fft.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/hirangren/Documents/Git/capstone-schwarz/hw/fft/fft.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
